Jan 26 00:55:46 twitter.py ERROR [1495]: 'NoneType' object has no attribute '__getitem__'
Jan 26 00:56:19 twitter.py INFO [1498]: Conexión con Twitter API
Jan 26 00:56:19 twitter.py INFO [1498]: Starting new HTTPS connection (1): api.twitter.com
Jan 26 00:56:19 twitter.py ERROR [1498]: Error al conectar con Twitter, verificar las credenciales.
Jan 26 00:56:19 twitter.py INFO [1498]: Starting new HTTPS connection (1): stream.twitter.com
Jan 26 00:56:19 twitter.py ERROR [1498]: HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json?delimited=length (Caused by <class 'socket.gaierror'>: [Errno -3] Temporary failure in name resolution)
Jan 26 00:57:34 twitter.py INFO [1503]: Conexión con Twitter API
Jan 26 00:57:34 twitter.py INFO [1503]: Starting new HTTPS connection (1): api.twitter.com
Jan 26 00:57:34 twitter.py ERROR [1503]: Error al conectar con Twitter, verificar las credenciales.
Jan 26 00:57:34 twitter.py INFO [1503]: Starting new HTTPS connection (1): stream.twitter.com
Jan 26 00:57:34 twitter.py ERROR [1503]: HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json?delimited=length (Caused by <class 'socket.gaierror'>: [Errno -3] Temporary failure in name resolution)
Jan 26 01:04:41 twitter.py INFO [1540]: Conexión con Twitter API
Jan 26 01:04:41 twitter.py INFO [1540]: Starting new HTTPS connection (1): api.twitter.com
Jan 26 01:04:41 twitter.py ERROR [1540]: Error al conectar con Twitter, verificar las credenciales.
Jan 26 01:04:41 twitter.py INFO [1540]: Starting new HTTPS connection (1): stream.twitter.com
Jan 26 01:04:41 twitter.py ERROR [1540]: HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json?delimited=length (Caused by <class 'socket.gaierror'>: [Errno -3] Temporary failure in name resolution)
Jan 26 01:04:47 twitter.py INFO [1543]: Conexión con Twitter API
Jan 26 01:04:47 twitter.py INFO [1543]: Starting new HTTPS connection (1): api.twitter.com
Jan 26 01:04:47 twitter.py ERROR [1543]: Error al conectar con Twitter, verificar las credenciales.
Jan 26 01:04:47 twitter.py INFO [1543]: Starting new HTTPS connection (1): stream.twitter.com
Jan 26 01:04:47 twitter.py ERROR [1543]: HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json?delimited=length (Caused by <class 'socket.gaierror'>: [Errno -3] Temporary failure in name resolution)
Jan 26 01:04:59 twitter.py INFO [1546]: Conexión con Twitter API
Jan 26 01:04:59 twitter.py INFO [1546]: Starting new HTTPS connection (1): api.twitter.com
Jan 26 01:04:59 twitter.py ERROR [1546]: Error al conectar con Twitter, verificar las credenciales.
Jan 26 01:04:59 twitter.py INFO [1546]: Starting new HTTPS connection (1): stream.twitter.com
Jan 26 01:04:59 twitter.py ERROR [1546]: HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json?delimited=length (Caused by <class 'socket.gaierror'>: [Errno -3] Temporary failure in name resolution)
Jan 26 01:05:00 twitter.py INFO [1549]: Conexión con Twitter API
Jan 26 01:05:00 twitter.py INFO [1549]: Starting new HTTPS connection (1): api.twitter.com
Jan 26 01:05:00 twitter.py ERROR [1549]: Error al conectar con Twitter, verificar las credenciales.
Jan 26 01:05:00 twitter.py INFO [1549]: Starting new HTTPS connection (1): stream.twitter.com
Jan 26 01:05:00 twitter.py ERROR [1549]: HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json?delimited=length (Caused by <class 'socket.gaierror'>: [Errno -3] Temporary failure in name resolution)
Jan 26 01:05:01 twitter.py INFO [1552]: Conexión con Twitter API
Jan 26 01:05:01 twitter.py INFO [1552]: Starting new HTTPS connection (1): api.twitter.com
Jan 26 01:05:01 twitter.py ERROR [1552]: Error al conectar con Twitter, verificar las credenciales.
Jan 26 01:05:01 twitter.py INFO [1552]: Starting new HTTPS connection (1): stream.twitter.com
Jan 26 01:05:01 twitter.py ERROR [1552]: HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json?delimited=length (Caused by <class 'socket.gaierror'>: [Errno -3] Temporary failure in name resolution)
